version: "3.3"

services: 
  api:
      depends_on:
      - db
      build:
        context: ./
        dockerfile: Dockerfile
        target: production
      container_name: api
      restart: always
      network_mode: "host"
      volumes:
       - .:/usr/src/app
      ports:
        - '4000:4000'

  db:
      image: postgres
      restart: always
      container_name: db
      network_mode: "host"
      environment:
        POSTGRES_PASSWORD: postgresPass
        POSTGRES_USER: postgresUser
        POSTGRES_DB: PresentationDB
      volumes:
         - ./PresentationDBData:/var/lib/postgresql
      ports:
         - 5432:5432


  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    network_mode: "host"
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    ports:
      - "9100:9100"
    restart: unless-stopped
 
    volumes:
      - '/:/host:ro,rslave' 
    

volumes:
      PresentationDBData:
      prometheus-data:
        driver: local
      grafana-data:
        driver: local
